export const customerApi={
    success:{
        data:[
            {
                id:1,
                name:"Kiên",
                status:true,
                create_at:"7/10/2021",
                update_at:"10/2/2022"
            },
            {
                id:2,
                name:"Trung",
                status:true,
                create_at:"4/10/2021",
                update_at:"1/2/2022"
            },
            {
                id:3,
                name:"Tuan",
                status:true,
                create_at:"8/10/2021",
                update_at:"04/12/2022"
            },
            {
                id:4,
                name:"Phuc",
                status:true,
                create_at:"8/6/2021",
                update_at:"10/2/2022"
            },
        ]
    }

}
